// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgcwOSvr9jQWF7Yj0WlY74KUy_sT7l18',
    appId: '1:282446267551:web:46746a9b7c5ce4efbf8eaa',
    messagingSenderId: '282446267551',
    projectId: 'simple-ecom-app',
    authDomain: 'simple-ecom-app.firebaseapp.com',
    storageBucket: 'simple-ecom-app.appspot.com',
    measurementId: 'G-JJ98V5CDXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GlFmNADxspaL_qMLO1Q5zDbt_bEpPzU',
    appId: '1:282446267551:android:06fde0addeb150c9bf8eaa',
    messagingSenderId: '282446267551',
    projectId: 'simple-ecom-app',
    storageBucket: 'simple-ecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8y8UOhwst5jvX0U_MBMHzxYPbX2JBqq4',
    appId: '1:282446267551:ios:efd8fab837ce89e4bf8eaa',
    messagingSenderId: '282446267551',
    projectId: 'simple-ecom-app',
    storageBucket: 'simple-ecom-app.appspot.com',
    iosClientId: '282446267551-823riibc9old8mdni6t2uaevohk3hcui.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleEcomApp',
  );
}
